// Auto-generated by make — do not edit
let buildVersion = "1.0.0"
let buildCommit = "eb1cc0a"
let buildBranch = "main"
let buildDate = "2026-09-26 00:32:56 UTC"
let buildSwiftVersion = "6.4"
let buildOS = "macOS 27.0"
