// Auto-generated by make — do not edit
let buildVersion = "1.2.0"
let buildCommit = "2193f9b"
let buildBranch = "main"
let buildDate = "2026-09-26 16:48:05 UTC"
let buildSwiftVersion = "6.4"
let buildOS = "macOS 27.0"
