// Auto-generated by make — do not edit
let buildVersion = "1.1.0"
let buildCommit = "f483945"
let buildBranch = "main"
let buildDate = "2026-09-26 16:46:29 UTC"
let buildSwiftVersion = "6.4"
let buildOS = "macOS 27.0"
