# dev(1) bash completion - generated by `dev completions bash`
_dev() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # `dev completions <shell>` subcommand
    if [ "${COMP_WORDS[1]}" = "completions" ] && [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ); return 0
    fi

    case "$prev" in
        -o|--output)
            COMPREPLY=( $(compgen -W "plain json" -- "$cur") ); return 0 ;;
        --context-strategy)
            COMPREPLY=( $(compgen -W "newest-first oldest-first sliding-window summarize strict" -- "$cur") ); return 0 ;;
        --audio-format)
            COMPREPLY=( $(compgen -W "wav pcm aac" -- "$cur") ); return 0 ;;
        --system-file|--mcp|-f|--file|--schema|--messages)
            COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;
        --demos)
            COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;
        -s|--system|--port|--host|--max-concurrent|--allowed-origins|--token|--mcp-timeout|--mcp-token|--temperature|--top-p|--seed|--max-tokens|--context-max-turns|--context-output-reserve|--input-device|--voice-name|--locale|--rate)
            return 0 ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--agent --allowed-origins --audio-format --benchmark --chat --code --context-max-turns --context-output-reserve --context-status --context-strategy --cors --count-tokens --debug --demos --file --footgun --help --host --i-know-what-im-doing --input-device --listen --locale --max-concurrent --max-tokens --mcp --mcp-timeout --mcp-token --messages --model-info --no-color --no-origin-check --output --permissive --port --public-health --quiet --rate --release --retry --schema --seed --serve --speak --stream --strict --system --system-file --temperature --timestamps --token --token-auto --top-p --update --version --voice-name -f -h -o -q -s -v completions" -- "$cur") ); return 0
    fi
    COMPREPLY=( $(compgen -f -- "$cur") ); return 0
}
complete -F _dev dev
